- name: Installing python 3
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Update system package repository
      apt_repository: "repo={{item}} update_cache=yes state=present"
      with_items:
        - ppa:fkrull/deadsnakes

    - name: Install Python
      apt: "name={{item}} state=present"
      with_items:
        - python3.5
        - python3.5-dev
        - python3.5-gdbm
        - python3.5-pip
