- name: Installing tmux
  hosts: all
  become: yes
  become_method: sudo

  vars:
    - tmux_version: "{{ ansible_env.TMUX_VERSION | default('2.1') }}"

  tasks:
    - name: Prepare the system for tmux install
      apt: "name{{item}} update_cache=yes"
      with_items:
        - exuberant-ctags
        - cmake
        - libevent-dev
        - libncurses5-dev
        - gcc

    - name: Download and build tmux
      command: "{{item}}"
      with_items:
        - "wget https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz"
        - "rm -Rf tmux-{{ tmux_version }}"
        - "tar xfz tmux-{{ tmux_version }}.tar.gz"

    - name: Install tmux
      command: "{{item}} chdir=tmux-{{ tmux_version }}"
      with_items:
        - pwd
        - ./configure
        - make
        - make install

    - name: Install tmuxinator
      command: "{{item}}"
      with_items:
        - apt-get install -qq ruby
        - gem install tmuxinator

    - name: Cleanup
      command: "{{item}}"
      with_items:
        - "rm -Rf tmux-{{ tmux_version }}*"
