- name: Installing ZShell
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Update system package repository
      apt_repository: "repo={{item}} update_cache=yes state=present"
      with_items:
        - ppa:keithw/mosh

    - name: Install ZShell
      apt: "name={{item}} state=present"
      sudo: true
      with_items:
        - wget
        - zsh
        - git
        - git-core

    - name: Install oh-my-zsh
      command: "{{item}}"
      sudo: true
      with_items:
        - sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

    - name: Set ZShell as default shell
      user: "name=vagrant shell=/usr/bin/zsh"
      sudo: true

    - name: Cleanup
      command: "{{item}}"
      sudo: true
      with_items:
        - rm install.sh
